project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Siyu Wu"
  site-url: https://sy5938.github.io/
  favicon: images/site-logo.png
  repo-url: https://github.com/sy5938/sy5938.github.io
  repo-actions: [edit, issue]
  page-footer:
    left: |
      © 2025-2026 Siyu Wu. All rights reserved. <br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Team"
        href: team.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Books"
        href: books.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    include-in-header: 
      - _includes/theme-preload.html
    include-after-body:
      - _includes/theme-toggle.html
    highlight-style: 
      light: github
      dark: dracula
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
